dist: bionic
language: c
compiler:
  - gcc

before_install:
  - npm install
  - sh ./setup.sh

before_script:
  - ./node_modules/.bin/commitlint-travis

script:
  - npm run build:css
  - npm run configure --tool xmake
  - xmake
  - npm run configure --tool cmake
  - cd build && cmake && make && cd ..
